/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mathcompiler;

import org.xtext.example.mathcompiler.MathDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MathDSLStandaloneSetup extends MathDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new MathDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
