/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mathcompiler;

import org.xtext.example.mathcompiler.AbstractMathDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MathDSLRuntimeModule extends AbstractMathDSLRuntimeModule {
}
