/*
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mathcompiler.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mathcompiler.mathdsl.ui.internal.MathdslActivator;

public class MathDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MathdslActivator.getInstance().getInjector("org.xtext.example.mathcompiler.MathDSL");
	}

}
