/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mathcompiler.mathAssignmentLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Let</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mathcompiler.mathAssignmentLanguage.Let#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.example.mathcompiler.mathAssignmentLanguage.Let#getBinding <em>Binding</em>}</li>
 *   <li>{@link org.xtext.example.mathcompiler.mathAssignmentLanguage.Let#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mathcompiler.mathAssignmentLanguage.MathAssignmentLanguagePackage#getLet()
 * @model
 * @generated
 */
public interface Let extends Expression
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.xtext.example.mathcompiler.mathAssignmentLanguage.MathAssignmentLanguagePackage#getLet_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.xtext.example.mathcompiler.mathAssignmentLanguage.Let#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Binding</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Binding</em>' containment reference.
   * @see #setBinding(Expression)
   * @see org.xtext.example.mathcompiler.mathAssignmentLanguage.MathAssignmentLanguagePackage#getLet_Binding()
   * @model containment="true"
   * @generated
   */
  Expression getBinding();

  /**
   * Sets the value of the '{@link org.xtext.example.mathcompiler.mathAssignmentLanguage.Let#getBinding <em>Binding</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Binding</em>' containment reference.
   * @see #getBinding()
   * @generated
   */
  void setBinding(Expression value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Expression)
   * @see org.xtext.example.mathcompiler.mathAssignmentLanguage.MathAssignmentLanguagePackage#getLet_Body()
   * @model containment="true"
   * @generated
   */
  Expression getBody();

  /**
   * Sets the value of the '{@link org.xtext.example.mathcompiler.mathAssignmentLanguage.Let#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Expression value);

} // Let
