/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mathcompiler.ide;

import org.xtext.example.mathcompiler.ide.AbstractMathDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MathDSLIdeModule extends AbstractMathDSLIdeModule {
}
