/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mathcompiler.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mathcompiler.MathDSLRuntimeModule;
import org.xtext.example.mathcompiler.MathDSLStandaloneSetup;
import org.xtext.example.mathcompiler.ide.MathDSLIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MathDSLIdeSetup extends MathDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    MathDSLRuntimeModule _mathDSLRuntimeModule = new MathDSLRuntimeModule();
    MathDSLIdeModule _mathDSLIdeModule = new MathDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_mathDSLRuntimeModule, _mathDSLIdeModule));
  }
}
