/*
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mathcompiler.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMathDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.example.mathcompiler.mathAssignmentLanguage.MathAssignmentLanguagePackage.eINSTANCE);
		return result;
	}
}
