/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mathcompiler.validation;

import org.xtext.example.mathcompiler.validation.AbstractMathDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MathDSLValidator extends AbstractMathDSLValidator {
}
