/*
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mathcompiler


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MathDSLStandaloneSetup extends MathDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new MathDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
