/*
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mathcompiler.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMathDSLScopeProvider extends DelegatingScopeProvider {
}
