/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mathcompiler.ui.contentassist;

import org.xtext.example.mathcompiler.ui.contentassist.AbstractMathDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MathDSLProposalProvider extends AbstractMathDSLProposalProvider {
}
