/*
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mathcompiler.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MathDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/mathcompiler/parser/antlr/internal/InternalMathDSL.tokens");
	}
}
