/*
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mathcompiler.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mathcompiler.parser.antlr.internal.InternalMathDSLParser;
import org.xtext.example.mathcompiler.services.MathDSLGrammarAccess;

public class MathDSLParser extends AbstractAntlrParser {

	@Inject
	private MathDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMathDSLParser createParser(XtextTokenStream stream) {
		return new InternalMathDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MathExp";
	}

	public MathDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MathDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
